/* Homeflow — deterministic household budget engine. No market forecasts.
 * Values are EUR. Recurring plan values are MONTHLY EQUIVALENTS, not cash dates.
 * Actual records never fall back to planned amounts. All exports are snapshots.
 */
(function(root,factory){const e=factory();if(typeof module==='object'&&module.exports)module.exports=e;else root.BudgetEngine=e;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION=1, MAX_MONEY=1e9;
const FREQUENCIES={monthly:12,weekly:52,biweekly:26,bimonthly:6,quarterly:4,semiannual:2,yearly:1,custom:null,once:null};
const KINDS=['income','benefit','expense','saving','investment'];
const CATEGORIES=['Housing','Food','Transportation','Children','Entertainment','Gifts and charity','Insurance','Loans','Personal care','Pets','Savings','Taxes','Subscriptions','Income','Other'];
const clone=o=>JSON.parse(JSON.stringify(o));
const sum=a=>a.reduce((s,n)=>s+n,0);
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
const text=(s,max=160)=>typeof s==='string'&&s.length<=max;
function validMonth(s){return typeof s==='string'&&/^\d{4}-(0[1-9]|1[0-2])$/.test(s)&&+s.slice(0,4)>=1900&&+s.slice(0,4)<=2200;}
function validDate(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s)||!validMonth(s.slice(0,7)))return false;const d=new Date(s+'T12:00:00Z');return !isNaN(d)&&d.toISOString().slice(0,10)===s;}
function monthIndex(s){return +s.slice(0,4)*12+(+s.slice(5,7)-1);}
function addMonths(s,n){const idx=monthIndex(s)+n;return String(Math.floor(idx/12)).padStart(4,'0')+'-'+String(idx%12+1).padStart(2,'0');}
function moneyValid(n,nullable=false){return nullable&&n===null||typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=MAX_MONEY;}
function assert(b,msg){if(!b)throw new Error(msg);}
function validate(s){
 assert(s&&s.schema==='homeflow'&&s.version===VERSION,'Unsupported file format / Μη υποστηριζόμενο αρχείο.');
 assert(validMonth(s.month),'Invalid month.');assert(text(s.household?.name,100),'Invalid household name.');
 assert(Array.isArray(s.household.members)&&s.household.members.length>=1&&s.household.members.length<=500,'The household must have 1–500 members.');
 const members=new Set();for(const m of s.household.members){assert(text(m.id,80)&&m.id&&!members.has(m.id),'Invalid / duplicate member ID.');members.add(m.id);assert(text(m.name,100)&&m.name.trim(),'Member name is required.');assert(['adult','child','dependent'].includes(m.role),'Invalid member role.');assert(typeof m.contributor==='boolean'&&moneyValid(m.weight),'Invalid allocation weight.');}
 assert(['equal','income','weight'].includes(s.household.split),'Invalid split rule.');
 assert(Array.isArray(s.plan)&&s.plan.length<=3000,'Too many planned items (maximum 3,000).');
 const ids=new Set();for(const p of s.plan){assert(text(p.id,80)&&p.id&&!ids.has(p.id),'Invalid / duplicate plan ID.');ids.add(p.id);assert(KINDS.includes(p.kind),'Invalid item kind.');assert(text(p.name)&&p.name.trim()&&text(p.category,80)&&p.category.trim(),'Description and category are required.');assert(moneyValid(p.amount,true),'Invalid amount.');assert(Object.hasOwn(FREQUENCIES,p.frequency),'Invalid frequency.');assert(typeof p.payments==='number'&&p.payments>=1&&p.payments<=366,'Payments per year must be 1–366.');assert(['household',...members].includes(p.member),'Unknown household member.');assert(['cash','voucher'].includes(p.funding),'Invalid funding type.');assert(p.funding==='cash'||p.kind==='expense','Only expenses can be paid with vouchers.');for(const k of ['essential','subscription','active','review'])assert(typeof p[k]==='boolean','Invalid flag: '+k);assert(!p.subscription||p.kind==='expense','A subscription must be an expense.');assert(!p.nextDate||validDate(p.nextDate),'Invalid renewal date.');assert(!p.startMonth||validMonth(p.startMonth),'Invalid start month.');assert(!p.endMonth||validMonth(p.endMonth),'Invalid end month.');assert(!(p.startMonth&&p.endMonth)||p.startMonth<=p.endMonth,'End month is before start month.');assert(p.frequency!=='once'||validMonth(p.startMonth),'A one-off item needs a month.');assert(text(p.note||'',400),'Note too long.');}
 assert(Array.isArray(s.actual)&&s.actual.length<=20000,'Too many actual records (maximum 20,000).');const tids=new Set();for(const t of s.actual){assert(text(t.id,80)&&t.id&&!tids.has(t.id),'Duplicate actual record ID.');tids.add(t.id);assert(validDate(t.date),'Invalid transaction date.');assert([...KINDS,'refund'].includes(t.kind),'Invalid actual kind.');assert(moneyValid(t.amount),'Invalid actual amount.');assert(text(t.name)&&t.name.trim()&&text(t.category,80),'Invalid transaction description.');assert(['household',...members].includes(t.member),'Unknown member in actual data.');assert(['cash','voucher'].includes(t.funding),'Invalid payment type.');assert(t.funding==='cash'||['expense','refund'].includes(t.kind),'Only spending/refunds can use vouchers.');assert(!t.planId||ids.has(t.planId),'Unknown plan reference.');}
 assert(Array.isArray(s.closedMonths)&&s.closedMonths.every(validMonth),'Invalid completion months.');
 assert(Array.isArray(s.goals)&&s.goals.length<=100,'Too many goals.');const gids=new Set(),links=new Set();for(const g of s.goals){assert(text(g.id,80)&&!gids.has(g.id)&&text(g.name,100)&&g.name.trim(),'Invalid goal.');gids.add(g.id);assert(['emergency','custom'].includes(g.type),'Invalid goal type.');assert(moneyValid(g.target)&&moneyValid(g.saved),'Invalid goal amounts.');assert(!g.entryId||ids.has(g.entryId),'Unknown goal contribution.');if(g.entryId){assert(!links.has(g.entryId),'A contribution cannot fund two goals.');links.add(g.entryId);assert(s.plan.find(p=>p.id===g.entryId).kind==='saving','Goals must link to a savings item.');}}
 const c=s.settings;assert(c&&moneyValid(c.buffer),'Invalid monthly buffer.');assert(typeof c.emergencyMonths==='number'&&c.emergencyMonths>=0&&c.emergencyMonths<=24,'Emergency months must be 0–24.');assert(typeof c.projectionMonths==='number'&&Number.isInteger(c.projectionMonths)&&c.projectionMonths>=1&&c.projectionMonths<=120,'Projection horizon must be 1–120 months.');for(const k of ['incomeGrowth','expenseGrowth'])assert(typeof c[k]==='number'&&Number.isFinite(c[k])&&c[k]>=-20&&c[k]<=30,'Invalid annual change.');for(const k of ['scenarioIncome','scenarioFlexible'])assert(typeof c[k]==='number'&&Number.isFinite(c[k])&&c[k]>=-100&&c[k]<=100,'Invalid scenario change.');assert(moneyValid(c.scenarioExtra),'Invalid extra expense.');assert(typeof s.isDemo==='boolean','Invalid demo flag.');
 return s;
}
function inMonth(p,m){return p.active&&(!p.startMonth||p.startMonth<=m)&&(!p.endMonth||p.endMonth>=m)&&(p.frequency!=='once'||p.startMonth===m);}
function monthly(p,m){if(!inMonth(p,m)||p.amount===null)return 0;return p.amount*(p.frequency==='once'?1:(p.frequency==='custom'?p.payments:FREQUENCIES[p.frequency])/12);}
function totalPlan(s,m=s.month){
 const items=s.plan.filter(p=>inMonth(p,m)), totals={income:0,benefit:0,expense:0,saving:0,investment:0,cashExpense:0,voucherExpense:0,essential:0,flexible:0,subscriptions:0,irregular:0,common:0};const byCategory=Object.create(null);
 for(const p of items){const a=monthly(p,m);totals[p.kind]+=a;if(p.kind==='expense'){const cash=p.funding==='cash';totals[cash?'cashExpense':'voucherExpense']+=a;totals[p.essential?'essential':'flexible']+=cash?a:0;if(p.subscription)totals.subscriptions+=a;if(p.frequency!=='monthly'&&p.frequency!=='once')totals.irregular+=cash?a:0;if(p.member==='household')totals.common+=cash?a:0;byCategory[p.category]=(byCategory[p.category]||0)+a;}}
 const missing=items.filter(p=>p.amount===null).length,review=items.filter(p=>p.review).length,unfunded=Math.max(0,totals.voucherExpense-totals.benefit);
 const beforeAllocations=totals.income-totals.cashExpense,free=beforeAllocations-totals.saving-totals.investment-s.settings.buffer;
 return {...totals,byCategory,missing,review,unfunded,beforeAllocations,free,capacity:(missing||review||unfunded>0.005)?null:Math.max(0,free),buffer:s.settings.buffer,hasData:items.some(p=>p.amount!==null&&p.amount>0),items};
}
function totalActual(s,m=s.month){const rows=s.actual.filter(t=>t.date.startsWith(m)),a={income:0,benefit:0,expense:0,cashExpense:0,voucherExpense:0,saving:0,investment:0,refund:0},byCategory=Object.create(null);for(const t of rows){if(t.kind==='expense'||t.kind==='refund'){const v=t.amount*(t.kind==='refund'?-1:1);a.expense+=v;a[t.funding==='cash'?'cashExpense':'voucherExpense']+=v;byCategory[t.category]=(byCategory[t.category]||0)+v;if(t.kind==='refund')a.refund+=t.amount;}else a[t.kind]+=t.amount;}
 const complete=s.closedMonths.includes(m),hasData=rows.length>0,free=a.income-a.cashExpense-a.saving-a.investment;
 return {...a,byCategory,free,complete,hasData,count:rows.length,capacity:complete?Math.max(0,free-s.settings.buffer):null,rows};}
function differences(s,m=s.month){const p=totalPlan(s,m),a=totalActual(s,m),cats=[...new Set([...Object.keys(p.byCategory),...Object.keys(a.byCategory)])];return cats.map(category=>({category,planned:p.byCategory[category]||0,actual:a.byCategory[category]||0,delta:(a.byCategory[category]||0)-(p.byCategory[category]||0)})).sort((a,b)=>b.planned-a.planned);}
function project(s,options={}){
 const n=options.months??s.settings.projectionMonths,shock=options.incomeChange??0,flex=options.flexChange??0,extra=options.extraExpense??0;assert(Number.isInteger(n)&&n>=1&&n<=120,'Invalid projection horizon.');assert([shock,flex,extra].every(Number.isFinite)&&shock>=-100&&flex>=-100&&extra>=0,'Invalid scenario.');let cumulative=0,totalIncome=0,totalExpense=0,totalSavings=0,totalInvest=0;
 const rows=[];for(let i=0;i<n;i++){const month=addMonths(s.month,i),p=totalPlan(s,month),gi=(1+s.settings.incomeGrowth/100)**(i/12),ge=(1+s.settings.expenseGrowth/100)**(i/12),income=p.income*gi*(1+shock/100),expenses=(p.essential+p.flexible*(1+flex/100))*ge+extra,free=income-expenses-p.saving-p.investment-s.settings.buffer;cumulative+=free;totalIncome+=income;totalExpense+=expenses;totalSavings+=p.saving;totalInvest+=p.investment;rows.push({month,income,expense:expenses,saving:p.saving,investment:p.investment,buffer:s.settings.buffer,free,cumulative,incomplete:!!(p.missing||p.review||p.unfunded>0.005)});}
 return {rows,cumulative,totalIncome,totalExpense,totalSavings,totalInvest,deficitMonths:rows.filter(r=>r.free<-.005).length,incomplete:rows.some(r=>r.incomplete)};
}
function goalStatus(s,g){const p=totalPlan(s),target=g.type==='emergency'?p.essential*s.settings.emergencyMonths:g.target,entry=s.plan.find(p=>p.id===g.entryId),contribution=entry?monthly(entry,s.month):0,gap=Math.max(0,target-g.saved);return {...g,target,contribution,gap,percent:target?Math.min(100,g.saved/target*100):null,months:gap===0?0:contribution>0?Math.ceil(gap/contribution):null,uncertain:!!(p.missing||p.review),funded:p.free>=-.005};}
function split(s){const contributors=s.household.members.filter(m=>m.contributor),p=totalPlan(s);if(!contributors.length)return[];let weights=contributors.map(m=>s.household.split==='income'?sum(s.plan.filter(e=>e.kind==='income'&&e.member===m.id).map(e=>monthly(e,s.month))):s.household.split==='weight'?m.weight:1);const total=sum(weights);if(total===0)return contributors.map(m=>({id:m.id,name:m.name,share:null,amount:null,income:0}));const totalCents=Math.round(p.common*100),exact=weights.map(w=>w/total*totalCents),cents=exact.map(Math.floor);let remainder=totalCents-sum(cents);exact.map((v,i)=>({i,f:v-cents[i]})).sort((a,b)=>b.f-a.f).slice(0,remainder).forEach(r=>cents[r.i]++);return contributors.map((m,i)=>({id:m.id,name:m.name,share:weights[i]/total,amount:cents[i]/100,income:sum(s.plan.filter(e=>e.kind==='income'&&e.member===m.id).map(e=>monthly(e,s.month)))}));}
function dateAddMonths(date,n){const month=addMonths(date.slice(0,7),n),d=Math.min(+date.slice(8,10),new Date(+month.slice(0,4),+month.slice(5,7),0).getDate());return month+'-'+String(d).padStart(2,'0');}
function nextDue(p,from){if(!p.active||!p.subscription||!p.nextDate||!validDate(from))return null;if(p.nextDate>=from)return p.nextDate;const step={monthly:1,bimonthly:2,quarterly:3,semiannual:6,yearly:12}[p.frequency];if(step){let n=Math.max(0,Math.floor((monthIndex(from)-monthIndex(p.nextDate))/step));let d=dateAddMonths(p.nextDate,n*step);while(d<from){n++;d=dateAddMonths(p.nextDate,n*step);}return d;}if(['weekly','biweekly'].includes(p.frequency)){const days=p.frequency==='weekly'?7:14;const count=Math.ceil((Date.parse(from)-Date.parse(p.nextDate))/(days*864e5));return new Date(Date.parse(p.nextDate)+count*days*864e5).toISOString().slice(0,10);}return null;}
return Object.freeze({VERSION,FREQUENCIES,KINDS,CATEGORIES,clone,sum,round,validMonth,validDate,addMonths,validate,monthly,inMonth,totalPlan,totalActual,differences,project,goalStatus,split,nextDue});
});
