/* Generic public templates. No personal source workbook data is distributed. */
(function(root){'use strict';
const uid=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
const labels={Housing:['Σπίτι & λογαριασμοί','Housing'],Food:['Τρόφιμα & φαγητό','Food'],Transportation:['Μετακινήσεις','Transportation'],Children:['Παιδιά','Children'],Entertainment:['Ψυχαγωγία','Entertainment'],'Gifts and charity':['Δώρα & προσφορές','Gifts and charity'],Insurance:['Ασφάλειες','Insurance'],Loans:['Δάνεια & οφειλές','Loans'],'Personal care':['Προσωπική φροντίδα & υγεία','Personal care & health'],Pets:['Κατοικίδια','Pets'],Savings:['Αποταμίευση','Savings'],Taxes:['Φόροι','Taxes'],Subscriptions:['Συνδρομές','Subscriptions'],Income:['Εισοδήματα','Income'],Other:['Άλλα','Other']};
function entry(p={}){return{id:uid(),kind:'expense',name:'',category:'Other',amount:null,frequency:'monthly',payments:12,member:'household',essential:true,funding:'cash',subscription:false,nextDate:'',startMonth:'',endMonth:'',active:true,review:false,note:'',...p};}
function blank(lang='el'){return{schema:'homeflow',version:1,isDemo:false,month:today().slice(0,7),household:{name:lang==='el'?'Το νοικοκυριό μου':'My household',members:[{id:'member-1',name:lang==='el'?'Άτομο 1':'Person 1',role:'adult',contributor:true,weight:1}],split:'income'},settings:{buffer:0,emergencyMonths:3,projectionMonths:12,incomeGrowth:0,expenseGrowth:0,scenarioIncome:0,scenarioFlexible:0,scenarioExtra:0},plan:[],actual:[],closedMonths:[],goals:[]};}
function starter(lang='el'){const s=blank(lang),l=(a,b)=>lang==='el'?a:b;s.plan=[entry({name:l('Καθαρός μισθός','Net salary'),kind:'income',category:'Income',member:'member-1'}),...[
 ['Ενοίκιο / στεγαστικό','Rent / mortgage','Housing',true],['Ηλεκτρικό ρεύμα','Electricity','Housing',true],['Νερό','Water','Housing',true],['Θέρμανση','Heating','Housing',true],['Κοινόχρηστα','Building maintenance','Housing',true],['Internet & τηλέφωνο','Internet & phone','Housing',true],['Τρόφιμα / supermarket','Groceries','Food',true],['Φαγητό έξω & delivery','Dining out & delivery','Food',false],['Καύσιμα / μετακινήσεις','Fuel / transport','Transportation',true],['Ασφάλεια οχήματος','Vehicle insurance','Transportation',true],['Υγεία & φάρμακα','Health & medicines','Personal care',true],['Ένδυση & φροντίδα','Clothing & personal care','Personal care',false],['Δάνεια / ελάχιστες δόσεις','Debt minimum payments','Loans',true],['Σχολείο & δραστηριότητες','School & activities','Children',true],['Κατοικίδια','Pet expenses','Pets',true],['Δώρα','Gifts','Gifts and charity',false],['Ψυχαγωγία','Entertainment','Entertainment',false],['Φόροι','Taxes','Taxes',true]
 ].map(([el,en,category,essential])=>entry({name:l(el,en),category,essential})),entry({name:l('Συνδρομή','Subscription'),category:'Subscriptions',essential:false,subscription:true})];return s;}
function demo(lang='el'){const s=blank(lang),l=(a,b)=>lang==='el'?a:b;s.isDemo=true;s.household.name=l('Παράδειγμα νοικοκυριού','Example household');s.household.members=[{id:'adult-1',name:l('Άτομο Α','Person A'),role:'adult',contributor:true,weight:1},{id:'adult-2',name:l('Άτομο Β','Person B'),role:'adult',contributor:true,weight:1},{id:'child-1',name:l('Παιδί','Child'),role:'child',contributor:false,weight:0}];
 const rows=[['income','Μισθός Α','Salary A','Income',2100,'adult-1',true],['income','Μισθός Β','Salary B','Income',1600,'adult-2',true],['expense','Ενοίκιο','Rent','Housing',720,'household',true],['expense','Ρεύμα & θέρμανση','Power & heating','Housing',145,'household',true],['expense','Νερό & κοινόχρηστα','Water & building fees','Housing',65,'household',true],['expense','Internet / κινητά','Internet / mobile','Housing',55,'household',true],['expense','Τρόφιμα','Groceries','Food',430,'household',true],['expense','Φαγητό έξω','Dining out','Food',110,'household',false],['expense','Μετακινήσεις','Transport','Transportation',180,'household',true],['expense','Σχολείο & δραστηριότητες','School & activities','Children',160,'household',true],['expense','Υγεία','Health','Personal care',70,'household',true],['expense','Προσωπικά έξοδα','Personal spending','Personal care',140,'household',false],['expense','Δόση δανείου','Loan payment','Loans',190,'household',true],['expense','Ψυχαγωγία','Entertainment','Entertainment',80,'household',false],['expense','Συνδρομή video','Video subscription','Subscriptions',12,'household',false],['expense','Συνδρομή μουσικής','Music subscription','Subscriptions',8,'household',false],['expense','Ετήσια ασφάλεια','Annual insurance','Insurance',360,'household',true],['saving','Μαξιλάρι ασφαλείας','Emergency reserve','Savings',150,'household',true],['saving','Ταξίδι','Holiday fund','Savings',100,'household',false],['investment','Επενδυτική καταβολή','Investment contribution','Savings',150,'household',false]];
 s.plan=rows.map(([kind,el,en,category,amount,member,essential],i)=>entry({id:'example-'+i,kind,name:l(el,en),category,amount,member,essential,subscription:category==='Subscriptions',frequency:i===16?'yearly':'monthly',nextDate:category==='Subscriptions'?s.month+'-'+(i===13?'20':'24'):''}));
 s.goals=[{id:'goal-e',name:l('Μαξιλάρι ασφαλείας','Emergency reserve'),type:'emergency',target:0,saved:2800,entryId:s.plan[17].id},{id:'goal-t',name:l('Ταξίδι','Holiday'),type:'custom',target:1500,saved:450,entryId:s.plan[18].id}];s.settings.buffer=120;
 s.actual=[{id:uid(),date:s.month+'-01',kind:'income',name:l('Μισθός Α','Salary A'),category:'Income',amount:2100,member:'adult-1',funding:'cash',planId:''},{id:uid(),date:s.month+'-02',kind:'income',name:l('Μισθός Β','Salary B'),category:'Income',amount:1600,member:'adult-2',funding:'cash',planId:''},{id:uid(),date:s.month+'-02',kind:'expense',name:l('Ενοίκιο','Rent'),category:'Housing',amount:720,member:'household',funding:'cash',planId:s.plan[2].id},{id:uid(),date:s.month+'-04',kind:'expense',name:l('Τρόφιμα','Groceries'),category:'Food',amount:87.5,member:'adult-1',funding:'cash',planId:s.plan[6].id}];return s;}
root.HomeData={uid,today,labels,entry,blank,starter,demo};
})(globalThis);
