/* Import/export boundaries. All parsing stays on the device. No backend. */
(function(root){'use strict';
const E=root.BudgetEngine,D=root.HomeData;
const HEADERS=['record_type','kind','description','category','amount','frequency','payments_per_year','member','essential','funding','subscription','next_date','date','start_month','end_month','active'];
const text=v=>v===undefined||v===null?'':String(v).trim();
function numeric(v,nullable=false){if(v===undefined||v===null||text(v)===''){if(nullable)return null;throw new Error('Amount is required.');}if(typeof v==='number'){if(!Number.isFinite(v))throw new Error('Invalid number.');return v;}let s=text(v).replace(/\s|€/g,'');if(/[.,]/.test(s)){if(/^\d{1,3}[.,]\d{3}$/.test(s))throw new Error('Ambiguous amount: '+s+'. Remove thousands separators.');if(s.includes('.')&&s.includes(',')){const dec=s.lastIndexOf('.')>s.lastIndexOf(',')?'.':',';s=s.replace(dec==='.'?/,/g:/\./g,'').replace(',','.');}else s=s.replace(',','.');}if(!/^\d+(?:\.\d{1,2})?$/.test(s))throw new Error('Use a positive amount, e.g. 1234.56 or 1234,56.');return +s;}
function bool(v,def){if(v===undefined||v===null||text(v)==='')return def;if(v===true||['true','1','yes','ναι'].includes(text(v).toLowerCase()))return true;if(v===false||['false','0','no','όχι'].includes(text(v).toLowerCase()))return false;throw new Error('Use TRUE or FALSE.');}
function parseCSV(textValue){let str=textValue.replace(/^\ufeff/,'');let explicit;if(/^sep=./i.test(str)){explicit=str[4];str=str.slice(str.indexOf('\n')+1);}const first=str.split(/\r?\n/)[0];const delim=explicit||(first.split(';').length>first.split(',').length?';':',');const rows=[],row=[];let field='',quote=false;for(let i=0;i<str.length;i++){const c=str[i];if(c==='"'){if(quote&&str[i+1]==='"'){field+='"';i++;}else if(quote)quote=false;else if(field==='')quote=true;else throw new Error('Malformed CSV quoting.');}else if(!quote&&c===delim){row.push(field);field='';}else if(!quote&&(c==='\n'||c==='\r')){if(c==='\r'&&str[i+1]==='\n')i++;row.push(field);field='';if(row.some(x=>x!==''))rows.push(row.slice());row.length=0;}else field+=c;if(rows.length>20000)throw new Error('CSV has too many rows.');}if(quote)throw new Error('Unclosed CSV quotation.');row.push(field);if(row.some(x=>x!==''))rows.push(row);return rows;}
function clean(s){E.validate(s);const select=(o,keys)=>Object.fromEntries(keys.map(k=>[k,o[k]]));return{schema:'homeflow',version:1,isDemo:s.isDemo,month:s.month,household:{name:s.household.name,split:s.household.split,members:s.household.members.map(m=>select(m,['id','name','role','contributor','weight']))},settings:select(s.settings,['buffer','emergencyMonths','projectionMonths','incomeGrowth','expenseGrowth','scenarioIncome','scenarioFlexible','scenarioExtra']),plan:s.plan.map(p=>select(p,['id','kind','name','category','amount','frequency','payments','member','essential','funding','subscription','nextDate','startMonth','endMonth','active','review','note'])),actual:s.actual.map(t=>select(t,['id','date','kind','name','category','amount','member','funding','planId'])),closedMonths:[...new Set(s.closedMonths)],goals:s.goals.map(g=>select(g,['id','name','type','target','saved','entryId']))};}
function parseTables(sheets,month){const output={format:'template',plan:[],actual:[],warnings:[],errors:[]};
for(const sheet of sheets){if(['guide','lists','οδηγίες'].includes(sheet.name.toLowerCase()))continue;const row0=sheet.rows.findIndex(r=>r.some(v=>text(v).toLowerCase()==='record_type'));if(row0<0)continue;const headers=sheet.rows[row0].map(v=>text(v).toLowerCase());for(const required of ['record_type','kind','description','category','amount'])if(!headers.includes(required))output.errors.push(sheet.name+': missing '+required);if(output.errors.length)continue;
for(let i=row0+1;i<sheet.rows.length;i++){const r=sheet.rows[i];if(!r.some(v=>v!==null&&v!==undefined&&text(v)!==''))continue;try{const o=Object.fromEntries(headers.map((h,j)=>[h,r[j]]));if(!['plan','actual'].includes(text(o.record_type)))throw new Error('record_type must be plan or actual.');const kind=text(o.kind);if(!(o.record_type==='actual'?[...E.KINDS,'refund']:E.KINDS).includes(kind))throw new Error('Unknown kind.');const name=text(o.description),category=text(o.category);if(!name||!category)throw new Error('Description and category are required.');const member=text(o.member)||'household',funding=text(o.funding)||'cash',amount=numeric(o.amount,o.record_type==='plan');
if(o.record_type==='plan'){output.plan.push(D.entry({kind,name,category,amount,frequency:text(o.frequency)||'monthly',payments:text(o.payments_per_year)?numeric(o.payments_per_year):12,member,essential:bool(o.essential,true),funding,subscription:bool(o.subscription,false),nextDate:text(o.next_date),startMonth:text(o.start_month),endMonth:text(o.end_month),active:bool(o.active,true)}));}else{const date=text(o.date);if(!E.validDate(date))throw new Error('Actual date must be YYYY-MM-DD.');output.actual.push({id:D.uid(),kind,name,category,amount,member,funding,date,planId:''});}}catch(e){output.errors.push(sheet.name+' / '+(i+1)+': '+e.message);}}
}
if(!output.plan.length&&!output.actual.length&&!output.errors.length)output.errors.push('No Budget / Actual template rows found. Use the downloadable template.');return output;}
function parseLegacy(sheets,month){const result={format:'legacy',plan:[],actual:[],warnings:[],errors:[]};const exp=sheets.find(s=>s.name.toLowerCase()==='monthly expenses');if(!exp)return null;const h=exp.rows.findIndex(r=>r.some(v=>text(v).toLowerCase()==='description'));if(h<0){result.errors.push('Monthly expenses has no Description header.');return result;}const headers=exp.rows[h].map(v=>text(v).toLowerCase());const ix=n=>headers.indexOf(n);if(['description','category','projected cost','actual cost'].some(n=>ix(n)<0)){result.errors.push('The legacy workbook needs Description, Category, Projected cost and Actual cost.');return result;}
for(let i=h+1;i<exp.rows.length;i++){const r=exp.rows[i],name=text(r[ix('description')]),category=text(r[ix('category')]);if(!name||!category)continue;try{const kind=category.toLowerCase()==='savings'?(/invest/i.test(name)?'investment':'saving'):'expense',p=D.entry({kind,name,category,amount:numeric(r[ix('projected cost')],true),essential:false,subscription:category.toLowerCase()==='subscriptions',note:'Legacy workbook: monthly equivalent. Essential classification needs review.'});result.plan.push(p);const actual=numeric(r[ix('actual cost')],true);if(actual!==null)result.actual.push({id:D.uid(),date:month+'-01',kind,name,category,amount:actual,member:'household',funding:'cash',planId:p.id});}catch(e){result.errors.push('Monthly expenses / '+(i+1)+': '+e.message);}}
const overview=sheets.find(s=>s.name.toLowerCase()==='budget overview');if(overview){const hr=overview.rows.findIndex(r=>r.some(v=>text(v).toLowerCase()==='projected')&&r.some(v=>text(v).toLowerCase()==='actual'));if(hr>=0){const projected=overview.rows[hr].findIndex(v=>text(v).toLowerCase()==='projected'),actual=overview.rows[hr].findIndex(v=>text(v).toLowerCase()==='actual');for(let i=hr+1;i<overview.rows.length;i++){const r=overview.rows[i],name=text(r[projected-1]);if(!name||/^total income/i.test(name))break;if(!/income/i.test(name))continue;try{const review=/edenred|voucher|benefit/i.test(name),p=D.entry({kind:'income',name,category:'Income',amount:numeric(r[projected],true),review,note:review?'Split cash income from restricted benefits before using the investment capacity.':'Already a monthly equivalent in the original workbook; do not apply 14/12 again.'});result.plan.push(p);const a=numeric(r[actual],true);if(a!==null&&!review)result.actual.push({id:D.uid(),kind:'income',name,category:'Income',amount:a,date:month+'-01',member:'household',funding:'cash',planId:p.id});}catch(e){result.errors.push('Budget overview / '+(i+1)+': '+e.message);}}}}
result.warnings.push('Οι αρχικές κατηγορίες διατηρούνται. Η κατηγορία Savings γίνεται αποταμίευση ή επένδυση, όχι κατανάλωση. / Savings is classified separately from spending.');result.warnings.push('Τα εισοδήματα του παλιού Excel είναι ήδη μηνιαία ισοδύναμα. Δεν εφαρμόζεται ξανά 14/12. / Legacy income is already monthly-normalised.');result.warnings.push('Σημείωσε εσύ ποια έξοδα είναι απαραίτητα και σε ποιο μέλος ανήκουν. Δεν γίνεται υπόθεση με βάση ονόματα. / Review essential flags and member allocation.');if(result.plan.some(p=>p.review))result.warnings.push('Μικτό εισόδημα / παροχές χρειάζεται διαχωρισμό. Το περιθώριο επένδυσης μένει σε αναμονή. Αυτή η μικτή γραμμή δεν εισάγεται στα πραγματικά εισοδήματα. / Mixed benefits need review.');result.warnings.push('Προαιρετικά: τα Actual costs θα καταχωρηθούν ως μηνιαία σύνολα στον επιλεγμένο μήνα, όχι ως ημερήσιο ιστορικό. / Optional actual values are monthly summaries, not daily transactions.');return result;}
function shareClean(s){return s?.schema==='homeflow-workspace'?root.HomeScenarios.clean(s):clean(s);}
async function readFile(file,month){if(file.size>5*1024*1024)throw new Error('Το αρχείο πρέπει να είναι έως 5 MB / maximum 5 MB.');const ext=file.name.split('.').pop().toLowerCase();if(ext==='json'){const data=JSON.parse((await file.text()).replace(/^\ufeff/,''));return{format:data?.schema==='homeflow-workspace'?'workspace-backup':'backup',state:shareClean(data),warnings:[],errors:[]};}let sheets,warnings=[];if(ext==='csv')sheets=[{name:'CSV',rows:parseCSV(await file.text())}];else if(ext==='xlsx'){const book=await root.HomeXlsx.read(await file.arrayBuffer());sheets=book.sheets;warnings=book.warnings;}else throw new Error('Χρησιμοποίησε .xlsx, .csv ή .json / Use .xlsx, .csv or .json.');const result=parseLegacy(sheets,month)||parseTables(sheets,month);result.warnings.push(...warnings.slice(0,20));return result;}
function fingerprint(p,actual=false){return JSON.stringify(actual?[p.date,p.kind,p.name,p.category,p.amount,p.member,p.funding]:[p.kind,p.name,p.category,p.amount,p.frequency,p.payments,p.member,p.essential,p.funding,p.subscription,p.startMonth,p.endMonth,p.active,p.review]);}
function merge(s,imp,{includeActual=false,skipDuplicates=true}={}){if(imp.errors.length)throw new Error('Fix the import errors first.');const next=clean(s);next.isDemo=false;const memberMap=new Map([['household','household']]);for(const m of next.household.members){memberMap.set(m.id,m.id);memberMap.set(m.name,m.id);}const resolve=name=>{if(memberMap.has(name))return memberMap.get(name);const id=D.uid();next.household.members.push({id,name,role:'adult',contributor:true,weight:1});memberMap.set(name,id);return id;};const planIds=new Map(),seenP=new Map(next.plan.map(p=>[fingerprint(p),p.id])),seenA=new Set(next.actual.map(t=>fingerprint(t,true)));let addedPlan=0,addedActual=0,skipped=0;
for(const original of imp.plan){const p={...original,member:resolve(original.member)};const f=fingerprint(p);if(skipDuplicates&&seenP.has(f)){skipped++;planIds.set(original.id,seenP.get(f));continue;}const old=p.id;p.id=D.uid();planIds.set(old,p.id);next.plan.push(p);seenP.set(f,p.id);addedPlan++;}
if(includeActual)for(const original of imp.actual){const t={...original,member:resolve(original.member),id:D.uid(),planId:planIds.get(original.planId)||''};const f=fingerprint(t,true);if(skipDuplicates&&seenA.has(f)){skipped++;continue;}next.actual.push(t);seenA.add(f);addedActual++;}E.validate(next);return{state:next,addedPlan,addedActual,skipped};}
function safeCell(v){const s=String(v??'');return /^[\s]*[=+@-]/.test(s)?"'"+s:s;}
function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>'"'+safeCell(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');}
function toRows(s,which='both'){const rows=[HEADERS],name=id=>s.household.members.find(m=>m.id===id)?.name||'household';if(which!=='actual')for(const p of s.plan)rows.push(['plan',p.kind,p.name,p.category,p.amount??'',p.frequency,p.payments,name(p.member),p.essential,p.funding,p.subscription,p.nextDate,'',p.startMonth,p.endMonth,p.active]);if(which!=='plan')for(const t of s.actual)rows.push(['actual',t.kind,t.name,t.category,t.amount,'','',''+name(t.member),'',t.funding,'','',t.date,'','','']);return rows;}
function download(data,name,type='application/octet-stream'){const b=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function strip(s,{actual=false,names=true}={}){const c=clean(s);c.isDemo=false;if(!actual){c.actual=[];c.closedMonths=[];}if(names){c.household.name='Household';c.household.members.forEach((m,i)=>m.name='Person '+(i+1));c.plan.forEach((p,i)=>{p.name=p.category+' '+(i+1);p.note='';});c.actual.forEach((t,i)=>t.name=t.category+' '+(i+1));c.goals.forEach((g,i)=>g.name=g.type==='emergency'?'Emergency reserve':'Goal '+(i+1));}return c;}
const b64=b=>{let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');};
const unb64=s=>{if(s.length>100000||!/^[A-Za-z0-9_-]+$/.test(s))throw new Error('Invalid or oversized sharing link.');return Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));};
async function transform(bytes,ctor,format){const stream=new Blob([bytes]).stream().pipeThrough(new ctor(format)),reader=stream.getReader(),chunks=[];let length=0;while(true){const r=await reader.read();if(r.done)break;length+=r.value.length;if(length>2e6){await reader.cancel();throw new Error('Shared budget is too large.');}chunks.push(r.value);}const result=new Uint8Array(length);let n=0;for(const c of chunks){result.set(c,n);n+=c.length;}return result;}
async function key(password,salt){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},k,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function shareEncode(s,password=''){let bytes=new TextEncoder().encode(JSON.stringify(shareClean(s))),codec='j';if(bytes.length>2e6)throw new Error('Too much data for a shared link. Export a private JSON backup instead.');if(typeof CompressionStream!=='undefined'){bytes=await transform(bytes,CompressionStream,'gzip');codec='z';}if(password){if(!crypto?.subtle)throw new Error('Password protection requires HTTPS or a supported local browser.');if(password.length<8)throw new Error('Use a password of at least 8 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(password,salt),enc=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,bytes));return 'h1e'+codec+'.'+b64(salt)+'.'+b64(iv)+'.'+b64(enc);}return'h1'+codec+'.'+b64(bytes);}
async function shareDecode(payload,password=''){let bytes,codec;const parts=payload.split('.');if(parts[0]==='h1ej'||parts[0]==='h1ez'){if(parts.length!==4)throw new Error('Invalid sharing link.');codec=parts[0].slice(-1);if(!crypto?.subtle)throw new Error('Decryption requires a modern secure browser.');const salt=unb64(parts[1]),iv=unb64(parts[2]);if(salt.length!==16||iv.length!==12)throw new Error('Invalid sharing parameters.');try{bytes=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv},await key(password,salt),unb64(parts[3])));}catch(_){throw new Error('Λάθος κωδικός ή αλλοιωμένος σύνδεσμος / Wrong password or damaged link.');}}else{if(parts.length!==2||!['h1j','h1z'].includes(parts[0]))throw new Error('Unknown sharing format.');codec=parts[0].slice(-1);bytes=unb64(parts[1]);}if(codec==='z'){if(typeof DecompressionStream==='undefined')throw new Error('This link needs a current browser.');bytes=await transform(bytes,DecompressionStream,'gzip');}if(bytes.length>2e6)throw new Error('Shared data is too large.');return shareClean(JSON.parse(new TextDecoder().decode(bytes)));}
root.HomeIO={HEADERS,numeric,parseCSV,parseTables,parseLegacy,readFile,clean,merge,fingerprint,csv,toRows,download,strip,shareEncode,shareDecode};
})(globalThis);
