/* Minimal READ-ONLY XLSX/ZIP reader. No macros, formulas or external entities run.
 * Uses the browser's native DecompressionStream('deflate-raw'). Not XLS/XLSM.
 * Limits compressed file, total expansion, individual entries and cell count.
 */
(function(root){'use strict';
const LIMIT=40*1024*1024,ENTRY=10*1024*1024;
function err(s){throw new Error(s);}
function xml(s){if(/<!DOCTYPE|<!ENTITY/i.test(s))err('Unsupported XML declarations.');const d=new DOMParser().parseFromString(s,'application/xml');if(d.getElementsByTagName('parsererror').length)err('Invalid spreadsheet XML.');return d;}
const all=(d,n)=>Array.from(d.getElementsByTagNameNS('*',n));
async function unzip(buffer){const b=new Uint8Array(buffer),v=new DataView(buffer);if(b.length>5*1024*1024)err('Maximum XLSX size: 5 MB.');let e=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--){if(v.getUint32(i,true)===0x06054b50){e=i;break;}}if(e<0)err('Invalid XLSX / ZIP file.');const count=v.getUint16(e+10,true),off=v.getUint32(e+16,true);if(count>500||off>=b.length)err('Unsupported XLSX archive.');let pos=off,total=0;const files=Object.create(null);
 for(let i=0;i<count;i++){if(pos+46>b.length||v.getUint32(pos,true)!==0x02014b50)err('Invalid ZIP directory.');const flags=v.getUint16(pos+8,true),method=v.getUint16(pos+10,true),crc=v.getUint32(pos+16,true),size=v.getUint32(pos+20,true),out=v.getUint32(pos+24,true),nl=v.getUint16(pos+28,true),xl=v.getUint16(pos+30,true),cl=v.getUint16(pos+32,true),local=v.getUint32(pos+42,true);if(pos+46+nl+xl+cl>b.length)err('Truncated ZIP entry.');const name=new TextDecoder().decode(b.slice(pos+46,pos+46+nl));pos+=46+nl+xl+cl;total+=out;if(total>LIMIT||out>ENTRY||flags&1||local===0xffffffff||size===0xffffffff)err('Encrypted, oversized or ZIP64 files are not supported.');if(name.includes('..')||name.startsWith('/'))err('Invalid ZIP path.');if(files[name])err('Duplicate ZIP path.');files[name]={method,crc,size,out,local};}
 const read=async name=>{const f=files[name];if(!f)return null;const o=f.local;if(o+30>b.length||v.getUint32(o,true)!==0x04034b50)err('Invalid local ZIP record.');const start=o+30+v.getUint16(o+26,true)+v.getUint16(o+28,true);if(start+f.size>b.length)err('Truncated compressed entry.');const data=b.slice(start,start+f.size);let raw;if(f.method===0)raw=data;else if(f.method===8){if(typeof DecompressionStream==='undefined')err('XLSX import needs a recent browser. Use CSV instead.');let stream;try{stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));}catch(_){err('This browser cannot read XLSX offline. Please use CSV or a recent Chrome / Safari.');}const reader=stream.getReader(),chunks=[];let n=0;while(true){const r=await reader.read();if(r.done)break;n+=r.value.length;if(n>ENTRY||n>f.out){await reader.cancel();err('Spreadsheet expansion limit exceeded.');}chunks.push(r.value);}raw=new Uint8Array(n);let p=0;for(const c of chunks){raw.set(c,p);p+=c.length;}}else err('Unsupported ZIP compression.');if(raw.length!==f.out)err('Damaged spreadsheet entry.');return new TextDecoder().decode(raw);};return{files,read};
}
function colIdx(ref){let n=0;for(const c of (ref.match(/^[A-Z]+/i)||[''])[0].toUpperCase())n=n*26+c.charCodeAt(0)-64;return n-1;}
async function readXlsx(buffer){const z=await unzip(buffer),book=await z.read('xl/workbook.xml'),rels=await z.read('xl/_rels/workbook.xml.rels');if(!book||!rels)err('No XLSX workbook found.');const wb=xml(book),rs=xml(rels),targets=Object.create(null);const date1904=["1","true"].includes(all(wb,"workbookPr")[0]?.getAttribute("date1904"));for(const r of all(rs,'Relationship')){if(r.getAttribute('TargetMode')==='External')continue;const t=r.getAttribute('Target')||'';if(t.includes('..'))continue;targets[r.getAttribute('Id')]=t.startsWith('/')?t.slice(1):'xl/'+t;}
 const ss=await z.read('xl/sharedStrings.xml');const strings=ss?all(xml(ss),'si').map(si=>all(si,'t').map(t=>t.textContent).join('')):[];const styleText=await z.read('xl/styles.xml');let dateStyles=[];
 if(styleText){const st=xml(styleText),formats={};for(const f of all(st,'numFmt'))formats[+f.getAttribute('numFmtId')]=f.getAttribute('formatCode');const cx=all(st,'cellXfs')[0];dateStyles=cx?Array.from(cx.children).map(x=>{const id=+x.getAttribute('numFmtId');const fmt=(formats[id]||'').replace(/"[^"]*"|\[[^\]]*\]|\\./g,'');return id>=14&&id<=22||/[yd]/i.test(fmt);}):[];}
 const sheets=[],warnings=[];let cells=0;for(const sh of all(wb,'sheet')){const id=sh.getAttribute('r:id')||sh.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');const path=targets[id];if(!path||!path.endsWith('.xml'))continue;const content=await z.read(path);if(!content)continue;const sx=xml(content),rows=[];
 for(const cell of all(sx,'c')){if(++cells>200000)err('Too many spreadsheet cells.');const ref=cell.getAttribute('r')||'',col=colIdx(ref),ri=parseInt(ref.replace(/^[A-Z]+/i,''),10)-1;if(col<0||col>1000||ri<0||ri>50000)err('Spreadsheet range too large.');const type=cell.getAttribute('t'),val=all(cell,'v')[0]?.textContent;let value=null;if(type==='inlineStr')value=all(cell,'t').map(t=>t.textContent).join('');else if(type==='s')value=strings[+val]??'';else if(type==='b')value=val==='1';else if(type==='e'){value=null;warnings.push('A formula/error cell has no usable value: '+sh.getAttribute('name')+'!'+ref);}else if(type==='str'||type==='d')value=val??null;else if(val!==undefined&&val!==''){value=Number(val);if(!Number.isFinite(value))err('Non-finite spreadsheet number.');if(dateStyles[+cell.getAttribute('s')])value=new Date((date1904?Date.UTC(1904,0,1):Date.UTC(1899,11,30))+Math.round(value*864e5)).toISOString().slice(0,10);}else if(all(cell,'f').length)warnings.push('Formula without cached result: '+sh.getAttribute('name')+'!'+ref);if(!rows[ri])rows[ri]=[];rows[ri][col]=value;}
 sheets.push({name:sh.getAttribute('name'),rows:Array.from({length:rows.length},(_,i)=>rows[i]||[])});}
 return{sheets,warnings};}
root.HomeXlsx={read:readXlsx};
})(globalThis);
