/* Generic synthetic test data only. Run: node tests/engine.test.js */
'use strict';
const assert=require('node:assert/strict');
if(!globalThis.crypto?.subtle)globalThis.crypto=require('node:crypto').webcrypto;
const E=globalThis.BudgetEngine=require('../budget-engine.js');
require('../data.js');require('../io.js');
const D=HomeData,I=HomeIO;
let passed=0;const failures=[];
const close=(x,y)=>assert.ok(Math.abs(x-y)<1e-7,`${x} != ${y}`);
async function test(name,fn){try{await fn();passed++;console.log('PASS',name);}catch(e){failures.push(name+': '+e.message);console.error('FAIL',name,e.message);}}
const plan=rows=>{const s=D.blank('en');s.month='2026-01';s.plan=rows.map(p=>D.entry(p));return E.validate(s);};
const entry=(kind,amount,extra={})=>({name:'Generic '+kind,category:kind==='income'?'Income':'Other',kind,amount,...extra});
const transaction=(kind,amount,extra={})=>({id:D.uid(),date:'2026-01-10',kind,amount,name:'Generic transaction',category:'Other',funding:'cash',member:'household',planId:'',...extra});
(async()=>{
await test('New household is empty and not a personal/demo budget',()=>{const s=D.blank();E.validate(s);assert.equal(s.plan.length,0);assert.equal(s.actual.length,0);assert.equal(s.isDemo,false);});
await test('All starter amounts remain unknown, not zero',()=>{const s=D.starter();E.validate(s);assert.ok(s.plan.every(p=>p.amount===null));assert.equal(E.totalPlan(s).capacity,null);});
await test('Fictional example cash-flow reconciles',()=>{const s=D.demo('en'),p=E.totalPlan(s);E.validate(s);close(p.income,3700);close(p.cashExpense,2395);close(p.saving,250);close(p.investment,150);close(p.capacity,785);});
await test('Monthly income less expenses',()=>{close(E.totalPlan(plan([entry('income',2000),entry('expense',1200)])).free,800);});
await test('Saving and investing reduce remainder, not consumption',()=>{const p=E.totalPlan(plan([entry('income',2000),entry('expense',1000),entry('saving',200),entry('investment',150)]));close(p.expense,1000);close(p.free,650);});
await test('Cushion deducted exactly once',()=>{const s=plan([entry('income',1500),entry('expense',500)]);s.settings.buffer=100;close(E.totalPlan(s).capacity,900);});
await test('Deficit is negative, investment capacity floors at zero',()=>{const p=E.totalPlan(plan([entry('income',100),entry('expense',200)]));close(p.free,-100);close(p.capacity,0);});
await test('Missing amounts block capacity while explicit zero is valid',()=>{const s=plan([entry('income',1000),entry('expense',null)]);assert.equal(E.totalPlan(s).capacity,null);s.plan[1].amount=0;close(E.totalPlan(s).capacity,1000);});
await test('Review flags block capacity even with amounts',()=>{assert.equal(E.totalPlan(plan([entry('income',1200,{review:true})])).capacity,null);});
await test('Restricted benefits are not cash income',()=>{const p=E.totalPlan(plan([entry('income',1000),entry('benefit',100),entry('expense',80,{funding:'voucher'})]));close(p.income,1000);close(p.benefit,100);close(p.cashExpense,0);close(p.expense,80);close(p.free,1000);});
await test('Unfunded planned vouchers block capacity',()=>{assert.equal(E.totalPlan(plan([entry('income',1000),entry('expense',100,{funding:'voucher'})])).capacity,null);});
for(const [frequency,rate] of Object.entries({monthly:1,weekly:52/12,biweekly:26/12,bimonthly:.5,quarterly:1/3,semiannual:1/6,yearly:1/12}))await test('Monthly equivalent: '+frequency,()=>close(E.monthly(D.entry(entry('income',120,{frequency})),'2026-01'),120*rate));
await test('14 salaries per year normalized once',()=>{close(E.totalPlan(plan([entry('income',1500,{frequency:'custom',payments:14})])).income,1750);});
await test('One-off included only in selected month',()=>{const s=plan([entry('expense',300,{frequency:'once',startMonth:'2026-02'})]);close(E.totalPlan(s).cashExpense,0);close(E.totalPlan(s,'2026-02').cashExpense,300);close(E.totalPlan(s,'2026-03').cashExpense,0);});
await test('Paused and bounded rows excluded correctly',()=>{const s=plan([entry('expense',100,{active:false}),entry('expense',200,{startMonth:'2026-02',endMonth:'2026-03'})]);close(E.totalPlan(s).expense,0);close(E.totalPlan(s,'2026-02').expense,200);close(E.totalPlan(s,'2026-04').expense,0);});
await test('Actual records never fall back to plan',()=>{const s=plan([entry('income',2000),entry('expense',1000)]);const a=E.totalActual(s);close(a.income,0);close(a.expense,0);assert.equal(a.capacity,null);});
await test('Partial actual history has no investable capacity',()=>{const s=plan([]);s.actual=[transaction('income',1000),transaction('expense',20)];assert.equal(E.totalActual(s).capacity,null);});
await test('Completed actual cash flow deducts cushion and transfers',()=>{const s=plan([]);s.actual=[transaction('income',1000),transaction('expense',400),transaction('saving',100),transaction('investment',50)];s.settings.buffer=50;s.closedMonths=['2026-01'];close(E.totalActual(s).free,450);close(E.totalActual(s).capacity,400);});
await test('Refunds reduce consumption without inflating income',()=>{const s=plan([]);s.actual=[transaction('expense',100),transaction('refund',30)];close(E.totalActual(s).expense,70);close(E.totalActual(s).income,0);close(E.totalActual(s).free,-70);});
await test('Actual month filtering',()=>{const s=plan([]);s.actual=[transaction('income',100),transaction('income',200,{date:'2026-02-10'})];close(E.totalActual(s).income,100);});
await test('Category difference uses actual minus plan',()=>{const s=plan([entry('expense',100)]);s.actual=[transaction('expense',120)];close(E.differences(s)[0].delta,20);});
await test('Projection cumulative remainder is not an investment balance',()=>{const s=plan([entry('income',1000),entry('expense',500),entry('saving',100)]);const r=E.project(s);close(r.cumulative,4800);close(r.totalSavings,1200);});
await test('Projection includes one-off once',()=>{const s=plan([entry('income',1000),entry('expense',500,{frequency:'once',startMonth:'2026-02'})]);close(E.project(s).cumulative,11500);});
await test('Income shock, flexible adjustment and extra expense',()=>{const s=plan([entry('income',1000),entry('expense',400),entry('expense',100,{essential:false})]);close(E.project(s,{months:1,incomeChange:-10,flexChange:-50,extraExpense:10}).cumulative,440);});
await test('Annual growth compounds from first month baseline',()=>{const s=plan([entry('income',1000)]);s.settings.incomeGrowth=12;close(E.project(s,{months:13}).rows[0].income,1000);close(E.project(s,{months:13}).rows[12].income,1120);});
await test('Projection reports incomplete assumptions',()=>{assert.equal(E.project(plan([entry('expense',null)])).incomplete,true);});
await test('Goal links do not duplicate monthly savings',()=>{const s=plan([entry('income',1000),entry('saving',100)]);s.goals=[{id:'g',name:'Reserve',type:'custom',target:1000,saved:100,entryId:s.plan[1].id}];E.validate(s);close(E.goalStatus(s,s.goals[0]).months,9);close(E.totalPlan(s).saving,100);close(E.totalPlan(s).free,900);});
await test('Emergency reserve uses chosen essential cash spending',()=>{const s=plan([entry('expense',100),entry('expense',80,{essential:false}),entry('expense',20,{funding:'voucher'})]);const g={id:'g',name:'Reserve',type:'emergency',target:0,saved:0,entryId:''};close(E.goalStatus(s,g).target,300);});
await test('A savings line cannot be assigned to two goals',()=>{const s=plan([entry('saving',100)]);s.goals=[1,2].map(n=>({id:'g'+n,name:'Goal '+n,type:'custom',target:100,saved:0,entryId:s.plan[0].id}));assert.throws(()=>E.validate(s));});
await test('Shared split preserves cents across three adults',()=>{const s=plan([entry('expense',100)]);s.household.split='equal';s.household.members=[1,2,3].map(i=>({id:'p'+i,name:'Person '+i,role:'adult',contributor:true,weight:1}));const r=E.split(s);close(r.reduce((a,b)=>a+b.amount,0),100);assert.deepEqual(r.map(p=>p.amount),[33.34,33.33,33.33]);});
await test('Income-based split ignores household unassigned income',()=>{const s=plan([entry('income',1000,{member:'member-1'}),entry('income',500,{member:'household'}),entry('expense',100)]);close(E.split(s)[0].amount,100);});
await test('Zero income weights stay unresolved',()=>{assert.equal(E.split(plan([entry('expense',100)]))[0].amount,null);});
await test('Jan 31 monthly renewal clamps February and restores March 31',()=>{const p=D.entry(entry('expense',10,{subscription:true,nextDate:'2026-01-31'}));assert.equal(E.nextDue(p,'2026-02-01'),'2026-02-28');assert.equal(E.nextDue(p,'2026-03-01'),'2026-03-31');});
await test('Paused subscription has no next due date',()=>{assert.equal(E.nextDue(D.entry(entry('expense',10,{subscription:true,nextDate:'2026-01-01',active:false})),'2026-02-01'),null);});
await test('Dates reject impossible days and accept leap years',()=>{assert.equal(E.validDate('2026-02-29'),false);assert.equal(E.validDate('2028-02-29'),true);assert.equal(E.validDate('2026-13-01'),false);});
await test('Invalid negatives, non-numeric and duplicate IDs are rejected',()=>{for(const amount of [-1,NaN,Infinity,'20'])assert.throws(()=>plan([entry('income',amount)]));const s=plan([entry('expense',10)]);s.plan.push({...s.plan[0]});assert.throws(()=>E.validate(s));});
await test('Special category cannot mutate object prototypes',()=>{const p=E.totalPlan(plan([entry('expense',30,{category:'__proto__'})]));close(p.byCategory.__proto__,30);assert.equal({}.polluted,undefined);});
await test('JSON backup exact round trip',()=>{const s=D.demo('en');assert.deepEqual(I.clean(JSON.parse(JSON.stringify(s))),s);});
await test('Unknown JSON keys stripped',()=>{const s=D.blank('en');s.secret='notwhitelisted';s.household.secret='x';assert.equal(I.clean(s).secret,undefined);assert.equal(I.clean(s).household.secret,undefined);});
await test('CSV quoting, delimiter, multiline and BOM',()=>{assert.deepEqual(I.parseCSV('\ufeffrecord_type;name;amount\r\nplan;"a;\"\"b\"\"\nline";12,50'),[['record_type','name','amount'],['plan','a;"b"\nline','12,50']]);});
await test('CSV decimal parsing is explicit, ambiguous separators rejected',()=>{close(I.numeric('12,50'),12.5);close(I.numeric('12.50'),12.5);assert.equal(I.numeric('',true),null);assert.throws(()=>I.numeric('1,234'));});
await test('CSV neutralizes formula-injection strings',()=>{assert.ok(I.csv([['=SUM(A1:A2)','+formula','@name']]).includes("'=SUM"));});
await test('Canonical CSV planned rows parse and merge',()=>{const s=plan([entry('income',1500),entry('expense',300)]);const imp=I.parseTables([{name:'CSV',rows:I.parseCSV(I.csv(I.toRows(s,'plan')))}],s.month);assert.deepEqual(imp.errors,[]);const m=I.merge(D.blank('en'),imp);assert.equal(m.addedPlan,2);close(E.totalPlan(m.state,s.month).free,1200);});
await test('Duplicate import is skipped atomically',()=>{const s=plan([entry('expense',100)]);const imp={plan:s.plan,actual:[],errors:[]};const m=I.merge(s,imp);assert.equal(m.addedPlan,0);assert.equal(m.skipped,1);});
await test('Actual import is opt-in',()=>{const s=plan([]),imp={plan:[],actual:[transaction('expense',20)],errors:[]};assert.equal(I.merge(s,imp).state.actual.length,0);assert.equal(I.merge(s,imp,{includeActual:true}).state.actual.length,1);});
await test('Failed import does not mutate existing data',()=>{const s=plan([]),before=JSON.stringify(s);assert.throws(()=>I.merge(s,{plan:[],actual:[],errors:['invalid']}));assert.equal(JSON.stringify(s),before);});
await test('Source-style import preserves blanks and Savings semantics',()=>{const imp=I.parseLegacy([{name:'Monthly expenses',rows:[['Description','Category','Projected cost','Actual cost'],['Investment account','Savings',25,0],['Rent','Housing',null,120]]}], '2026-01');assert.equal(imp.plan[0].kind,'investment');assert.equal(imp.plan[1].amount,null);assert.equal(imp.actual[0].amount,0);});
await test('Shared copies exclude actuals and descriptions by default',()=>{const s=D.demo('en'),c=I.strip(s);assert.equal(c.actual.length,0);assert.equal(c.closedMonths.length,0);assert.equal(c.household.name,'Household');assert.equal(c.household.members[0].name,'Person 1');assert.notEqual(c.plan[0].name,s.plan[0].name);assert.equal(c.plan[0].amount,s.plan[0].amount);});
await test('Share payload supports multilingual amounts and names',async()=>{const s=D.demo('el');assert.deepEqual(await I.shareDecode(await I.shareEncode(s)),s);});
await test('Password link decrypts only with matching password',async()=>{const s=D.blank('en'),payload=await I.shareEncode(s,'Strong-Test-Password');assert.ok(payload.startsWith('h1e'));assert.ok(!payload.includes('Strong-Test'));assert.deepEqual(await I.shareDecode(payload,'Strong-Test-Password'),s);await assert.rejects(()=>I.shareDecode(payload,'WrongPassword'));});
await test('Modified encrypted payload is rejected',async()=>{const payload=await I.shareEncode(D.blank(),'Safe-Test-Password');const p=payload.split('.');p[3]=(p[3][0]==='A'?'B':'A')+p[3].slice(1);await assert.rejects(()=>I.shareDecode(p.join('.'),'Safe-Test-Password'));});
await test('Malformed, oversized and unsupported sharing formats rejected',async()=>{for(const p of ['h9j.abcd','h1j.!!!!','h1j.'+'A'.repeat(100001)])await assert.rejects(()=>I.shareDecode(p));});
console.log(JSON.stringify({passed,failed:failures.length,failures},null,2));if(failures.length)process.exitCode=1;
})();
