'use strict';
const assert=require('node:assert/strict');
globalThis.BudgetEngine=require('../budget-engine.js');require('../data.js');require('../io.js');require('../scenarios.js');
const E=BudgetEngine,D=HomeData,IO=HomeIO,S=HomeScenarios;
let passed=0,failures=[];async function test(name,fn){try{await fn();passed++;console.log('PASS',name);}catch(e){failures.push(name+': '+e.message);console.error('FAIL',name,e.message);}}
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function doc(){const s=D.blank('en');s.month='2026-01';s.plan=[D.entry({id:'income',name:'Income',kind:'income',category:'Income',amount:2400}),D.entry({id:'rent',name:'Housing',category:'Housing',amount:700}),D.entry({id:'other',name:'Living',category:'Other',amount:400,essential:false}),D.entry({id:'saving',name:'Saving',kind:'saving',category:'Savings',amount:200}),D.entry({id:'invest',name:'Investment',kind:'investment',category:'Savings',amount:150})];s.settings.buffer=100;return s;}
(async()=>{
await test('Migration creates one scenario with all original fields',()=>{const d=doc(),w=S.create(d);assert.deepEqual(S.active(w).state,d);assert.equal(w.scenarios.length,1);});
await test('Migration and returned workspace do not alias input',()=>{const d=doc(),w=S.create(d);S.active(w).state.plan[0].amount=100;assert.equal(d.plan[0].amount,2400);});
await test('Exactly three scenarios including original are allowed',()=>{let w=S.create(doc());w=S.fork(w,'Two');w=S.fork(w,'Three');assert.equal(w.scenarios.length,3);assert.throws(()=>S.fork(w,'Four'));});
await test('Fork preserves original without shared references',()=>{const w=S.fork(S.create(doc()),'Copy');w.scenarios[1].state.plan[1].amount=99;assert.equal(w.scenarios[0].state.plan[1].amount,700);});
await test('Fork excludes actuals and complete months by default',()=>{const d=doc();d.actual=[{id:'a1',date:'2026-01-01',kind:'expense',name:'Buy',category:'Other',amount:10,member:'household',funding:'cash',planId:'rent'}];d.closedMonths=['2026-01'];const w=S.fork(S.create(d),'Copy');assert.equal(w.scenarios[0].state.actual.length,1);assert.equal(w.scenarios[1].state.actual.length,0);assert.equal(w.scenarios[1].state.closedMonths.length,0);});
await test('Opt-in actual copy preserves links without aliasing',()=>{const d=doc();d.actual=[{id:'a1',date:'2026-01-01',kind:'expense',name:'Buy',category:'Other',amount:10,member:'household',funding:'cash',planId:'rent'}];const w=S.fork(S.create(d),'Copy',true);assert.deepEqual(w.scenarios[0].state.actual,w.scenarios[1].state.actual);w.scenarios[1].state.actual[0].amount=20;assert.equal(w.scenarios[0].state.actual[0].amount,10);});
await test('Cannot delete final scenario',()=>{const w=S.create(doc());assert.throws(()=>S.remove(w,w.activeId));});
await test('Delete reference restores a valid reference and active ID',()=>{let w=S.fork(S.create(doc()),'Copy');w=S.remove(w,w.referenceId);assert.equal(w.referenceId,w.activeId);assert.equal(w.scenarios.length,1);});
await test('Comparison never sums alternative households',()=>{const w=S.fork(S.create(doc()),'Copy');const c=S.compare(w);close(c.results[0].first.free,850);close(c.results[1].first.free,850);close(c.results[1].delta.monthly,0);});
await test('More rent reduces free amount by exact delta',()=>{const w=S.fork(S.create(doc()),'Higher housing');w.scenarios[1].state.plan[1].amount+=125;const c=S.compare(w);close(c.results[1].delta.monthly,-125);close(c.results[1].delta.cumulative,-1500);});
await test('Common horizon overrides individual saved horizons',()=>{const w=S.fork(S.create(doc()),'Copy');w.scenarios[1].state.settings.projectionMonths=100;w.comparison.months=24;assert.ok(S.compare(w).results.every(s=>s.projection.rows.length===24));});
await test('Common month aligns dated one-offs across scenarios',()=>{const d=doc();d.plan.push(D.entry({name:'One-off',amount:200,frequency:'once',startMonth:'2026-02'}));const w=S.fork(S.create(d),'Copy');w.scenarios[1].state.month='2030-01';w.comparison.month='2026-02';const c=S.compare(w);assert.equal(c.results[0].first.expense,c.results[1].first.expense);close(c.results[0].first.expense,1300);});
await test('All per-scenario shock assumptions applied to summary and chart',()=>{const w=S.fork(S.create(doc()),'Shock');w.scenarios[1].state.settings.scenarioIncome=-10;w.scenarios[1].state.settings.scenarioFlexible=-25;w.scenarios[1].state.settings.scenarioExtra=50;const c=S.compare(w),s=c.results[1];close(s.first.free,660);close(s.projection.cumulative,7920);});
await test('Deficit shown negative, not as investable money',()=>{const w=S.create(doc());w.scenarios[0].state.settings.scenarioExtra=1000;const s=S.compare(w).results[0];close(s.first.free,-150);assert.equal(s.capacity,0);assert.equal(s.projection.deficitMonths,12);});
await test('Missing amounts withhold capacity and deltas',()=>{const w=S.fork(S.create(doc()),'Partial');w.scenarios[1].state.plan[1].amount=null;const s=S.compare(w).results[1];assert.equal(s.capacity,null);assert.equal(s.delta,null);assert.equal(s.incomplete,true);});
await test('Blank document is not a complete zero-cost budget',()=>{const s=S.compare(S.create(D.blank())).results[0];assert.equal(s.empty,true);assert.equal(s.capacity,null);});
await test('Explicit zeros are valid inputs',()=>{const d=doc();d.plan.forEach(p=>p.amount=0);const s=S.compare(S.create(d)).results[0];assert.equal(s.capacity,0);assert.equal(s.incomplete,false);});
await test('Later missing value invalidates comparison horizon',()=>{const d=doc();d.plan.push(D.entry({name:'Unknown future',amount:null,startMonth:'2026-06'}));const s=S.compare(S.create(d)).results[0];assert.equal(s.incomplete,true);});
await test('Unfunded vouchers block comparison capacity',()=>{const d=doc();d.plan.push(D.entry({name:'Voucher spend',amount:100,funding:'voucher'}));assert.equal(S.compare(S.create(d)).results[0].capacity,null);});
await test('Comparison does not mutate documents or start months',()=>{const w=S.fork(S.create(doc()),'Copy');w.comparison.month='2027-05';const original=JSON.stringify(w);S.compare(w);assert.equal(JSON.stringify(w),original);});
await test('Actual-only data not misreported as a spending forecast',()=>{const d=D.blank();d.actual=[{id:'a',date:d.month+'-01',kind:'expense',name:'Buy',category:'Other',amount:20,member:'household',funding:'cash',planId:''}];assert.equal(S.compare(S.create(d)).results[0].capacity,null);});
await test('Reference changes only delta basis',()=>{const w=S.fork(S.create(doc()),'Copy');w.scenarios[1].state.plan[1].amount=900;w.referenceId=w.scenarios[1].id;const c=S.compare(w);close(c.results[0].delta.monthly,200);close(c.results[1].delta.monthly,0);});
await test('Sharing strips every scenario name and document description',()=>{const w=S.fork(S.create(doc(),'Private'),'Also private'),s=S.strip(w);assert.deepEqual(s.scenarios.map(x=>x.name),['Scenario 1','Scenario 2']);assert.ok(!JSON.stringify(s).includes('Also private'));assert.equal(s.scenarios[0].state.household.name,'Household');});
await test('Whole comparison public link round-trips',async()=>{const w=S.fork(S.create(doc()),'Copy');assert.deepEqual(await IO.shareDecode(await IO.shareEncode(w)),w);});
await test('Whole comparison password link round-trips',async()=>{const w=S.fork(S.create(doc()),'Copy'),p=await IO.shareEncode(w,'synthetic-test-pass');assert.deepEqual(await IO.shareDecode(p,'synthetic-test-pass'),w);await assert.rejects(()=>IO.shareDecode(p,'incorrect-pass'));});
await test('Old single-document links remain compatible',async()=>{const d=doc();assert.deepEqual(await IO.shareDecode(await IO.shareEncode(d)),d);});
await test('Workspace backup reader distinguishes from single document',async()=>{const w=S.create(doc()),f={name:'synthetic.json',size:JSON.stringify(w).length,text:async()=>JSON.stringify(w)};const r=await IO.readFile(f,w.comparison.month);assert.equal(r.format,'workspace-backup');assert.deepEqual(r.state,w);});
await test('Unknown workspace keys are stripped',()=>{const w=S.create(doc());w.extra='bad';w.scenarios[0].extra='bad';assert.equal(S.clean(w).extra,undefined);assert.equal(S.clean(w).scenarios[0].extra,undefined);});
await test('Invalid IDs, references, counts, names and horizons rejected',()=>{const w=S.create(doc());for(const fn of [x=>x.activeId='none',x=>x.referenceId='none',x=>x.scenarios=[],x=>x.scenarios[0].name='',x=>x.comparison.months=0,x=>x.comparison.months=121,x=>x.comparison.month='not-a-month',x=>x.scenarios[0].state.plan[0].amount=-1]){const x=E.clone(w);fn(x);assert.throws(()=>S.clean(x));}});
console.log(JSON.stringify({passed,failed:failures.length,failures},null,2));if(failures.length)process.exitCode=1;
})();
